name: GMC
version: Beta 1.3.9
author: MCMainiac
website: http://bit.ly/MC-GMC

main: de.mcmainiac.gmc.Main

commands:
  gamemode:
    description: Change the game mode of a player
    usage: /gamemode <id> [player]
  gm:
    description: Change the game mode of a player
    usage: /gm <id> [player]
  gmh:
    description: Displays help for GMC
    usage: /gmh [page | command]
  gmi:
    description: Displays info about GMC
    usage: /gmi
  gmr:
    description: Reloads the config of GMC
    usage: /gmr
  gmonce:
    description: Allow a player to change his/her game mode only one time
    usage: /gmonce <player> [survival] [creative] [adventure] [spectator]
  gmtemp:
    description: Change the game mode of a player only temporary
    usage: /gmtemp <player> <game mode> <seconds>

  gm0:
    description: Change the game mode of a player to Survival
    usage: /gm0 [player]
  gm1:
    description: Change the game mode of a player to Creative
    usage: /gm1 [player]
  gm2:
    description: Change the game mode of a player to Adventure
    usage: /gm2 [player]
  gm3:
    description: Change the game mode of a player to Spectator
    usage: /gm3 [player]

  survival:
    description: Change the game mode of a player to Survival
    usage: /survival [player]
  creative:
    description: Change the game mode of a player to Creative
    usage: /creative [player]
  adventure:
    description: Change the game mode of a player to Adventure
    usage: /adventure [player]
  spectator:
    description: Change the game mode of a player to Spectator
    usage: /spectator [player]
